name: Deploy to Raspberry Pi

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on:
      - self-hosted
      - halo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Start the app
        run: |
          pnpm api start
      # - name: Restart app with PM2
      #   run: |
      #     pm2 startOrReload ecosystem.config.cjs
      #     pm2 save
